// Clipboard history manager, ported from Necrom4/ClipboardHistory.spoon
// (https://github.com/necrom4/ClipboardHistory.spoon), a Hammerspoon v1
// Spoon. Watches the pasteboard and keeps a searchable, persisted history
// of text, URLs, file paths and images, presented in a chooser.
//
// Differences from the v1 Spoon this ports:
// - No manual poll timer: hs.pasteboard.on("change", ...) is already
//   implemented by polling changeCount internally (per its own doc
//   comment), so this just registers a listener instead of running its
//   own hs.timer loop.
// - No "hidden zero-size styled text" trick to survive the chooser's own
//   substring filter: hs.chooser.setChoices() accepts a `(query) => [...]`
//   function directly ("the function is responsible for filtering"), so
//   this does its own fuzzy filtering and hands back exactly the rows it
//   wants, no workaround needed.
// - No right-click context menu: HSChooser has no row-right-click
//   callback at all in this API. chooser-options-bar.ts's shortcut legend
//   (Paste/Copy/Pin/Delete/Reveal) replaces it instead.
// - hs.json.encode/decode doesn't exist here -- this runs as plain
//   JavaScript, so JSON.stringify/JSON.parse do the same job natively.

import { Theme, chooserColor } from "./nord-theme";
import { attachOptionsBar, type ChoiceOption } from "./chooser-options-bar";

const MAX_HISTORY = 100;
const MAX_TEXT_LENGTH = 1024 * 1024; // 1 MB

const DATA_DIR = hs.fs.homeDirectory() + "/.config/Hammerspoon2/data/clipboard-history";
const IMAGE_DIR = DATA_DIR + "/images";
const HISTORY_FILE = DATA_DIR + "/history.json";

// Clipboard content an app flags as concealed or transient is never
// recorded, so e.g. a password copied from a password manager (or the
// macOS Passwords app) stays out of history.
const CONCEALED_TYPES = [
	"org.nspasteboard.ConcealedType",
	"org.nspasteboard.TransientType",
	"org.nspasteboard.AutoGeneratedType",
	"com.agilebits.onepassword",
];

type EntryKind = "text" | "url" | "file" | "image";

interface EntrySource {
	name: string | null;
	bundleID: string | null;
}

interface ClipEntry {
	kind: EntryKind;
	text?: string; // text/url/file
	path?: string; // image, on disk
	width?: number; // image
	height?: number; // image
	bytes: number;
	time: number; // Date.now()
	source: EntrySource | null;
	pinned?: boolean;
}

let history: ClipEntry[] = [];
let lastChangeCount = -1;
let chooser: HSChooser | null = null;
const iconCache = new Map<string, HSImage | null>();

// ============================================================
// CAPTURE
// ============================================================

function isConcealed(): boolean {
	return CONCEALED_TYPES.some((uti) => hs.pasteboard.hasType(uti));
}

function looksLikeURL(s: string): boolean {
	return /^[a-z][\w+.-]*:\/\//i.test(s);
}

function looksLikeFilePath(s: string): boolean {
	return s.startsWith("/") && !s.includes("\n") && hs.fs.attributes(s) !== null;
}

function classifyText(text: string): EntryKind {
	if (looksLikeURL(text)) return "url";
	if (looksLikeFilePath(text)) return "file";
	return "text";
}

function frontmostSource(): EntrySource | null {
	const app = hs.application.frontmost();
	return app ? { name: app.title, bundleID: app.bundleID } : null;
}

function captureText(source: EntrySource | null): ClipEntry | null {
	const text = hs.pasteboard.readString();
	if (!text || text.length > MAX_TEXT_LENGTH) return null;
	return { kind: classifyText(text), text, bytes: text.length, time: Date.now(), source };
}

function captureImage(source: EntrySource | null): ClipEntry | null {
	const img = hs.pasteboard.readImage();
	if (!img) return null;
	const filename = `${IMAGE_DIR}/clip-${Date.now()}-${Math.floor(Math.random() * 900000 + 100000)}.png`;
	if (!img.saveToFile(filename)) return null;
	const attrs = hs.fs.attributes(filename) as { size?: number } | null;
	return {
		kind: "image",
		path: filename,
		width: Math.floor(img.size.w),
		height: Math.floor(img.size.h),
		bytes: attrs?.size ?? 0,
		time: Date.now(),
		source,
	};
}

function entryEquals(a: ClipEntry, b: ClipEntry): boolean {
	if (a.kind !== b.kind) return false;
	if (a.kind === "image") return a.bytes === b.bytes && a.width === b.width && a.height === b.height;
	return a.text === b.text;
}

function deleteImageFile(entry: ClipEntry): void {
	if (entry.kind === "image" && entry.path) hs.fs.deletePath(entry.path);
}

function addEntry(entry: ClipEntry | null): boolean {
	if (!entry) return false;

	// A duplicate keeps the older entry's pinned flag and image file.
	const dupIndex = history.findIndex((item) => entryEquals(item, entry));
	if (dupIndex !== -1) {
		const dup = history[dupIndex]!;
		entry.pinned = entry.pinned || dup.pinned;
		if (entry.kind === "image" && dup.path && dup.path !== entry.path) {
			if (entry.path) hs.fs.deletePath(entry.path);
			entry.path = dup.path;
		}
		history.splice(dupIndex, 1);
	}

	history.unshift(entry);

	// Pinned entries don't count toward MAX_HISTORY and are never evicted.
	const kept: ClipEntry[] = [];
	let nonPinned = 0;
	for (const item of history) {
		if (item.pinned) {
			kept.push(item);
		} else {
			nonPinned++;
			if (nonPinned <= MAX_HISTORY) kept.push(item);
			else deleteImageFile(item);
		}
	}
	history = kept;
	saveHistory();
	return true;
}

function checkPasteboard(): void {
	const cc = hs.pasteboard.changeCount;
	if (cc === lastChangeCount) return;
	lastChangeCount = cc;

	if (isConcealed()) return;

	const source = frontmostSource();
	if (addEntry(captureText(source))) return;
	addEntry(captureImage(source));
}

// ============================================================
// PERSISTENCE
// ============================================================

function saveHistory(): void {
	hs.fs.write(HISTORY_FILE, JSON.stringify(history)); // atomic by default
}

function loadHistory(): ClipEntry[] {
	const attrs = hs.fs.attributes(HISTORY_FILE) as { size?: number } | null;
	if (!attrs?.size) return [];
	const raw = hs.fs.read(HISTORY_FILE, 0, attrs.size);
	if (!raw) return [];
	try {
		const parsed = JSON.parse(raw) as unknown;
		return Array.isArray(parsed) ? (parsed as ClipEntry[]) : [];
	} catch {
		return [];
	}
}

// ============================================================
// RESTORE / ACTIONS
// ============================================================

function restoreEntry(entry: ClipEntry): void {
	if (entry.kind === "image" && entry.path) {
		const img = HSImage.fromPath(entry.path);
		if (img) hs.pasteboard.writeImage(img);
	} else if (entry.text) {
		hs.pasteboard.writeString(entry.text);
	}
	lastChangeCount = hs.pasteboard.changeCount;
}

function paste(entry: ClipEntry): void {
	restoreEntry(entry);
	const i = history.indexOf(entry);
	if (i !== -1) {
		history.splice(i, 1);
		history.unshift(entry);
	}
	saveHistory();
	hs.eventtap.keyStroke(["cmd"], "v");
}

function revealOrOpen(entry: ClipEntry): void {
	if (entry.kind === "image" && entry.path) {
		const task = hs.task.create("/usr/bin/open", ["-R", entry.path], null, null, null);
		task.start();
	} else if (entry.kind === "url" && entry.text) {
		hs.urlevent.openURL(entry.text);
	}
}

export function clear(): void {
	for (const item of history) deleteImageFile(item);
	history = [];
	saveHistory();
	hs.ui.alert("Clipboard history cleared").duration(1).show();
	chooser?.refreshChoices();
}

// ============================================================
// SEARCH / FILTERING
// ============================================================

const VALID_TAGS = new Set(["text", "url", "file", "image", "pinned"]);

function parseQuery(query: string): { filter: string | null; rest: string } {
	const m = query.match(/^:(\w+)\s*(.*)$/);
	if (m && VALID_TAGS.has(m[1]!.toLowerCase())) {
		return { filter: m[1]!.toLowerCase(), rest: (m[2] ?? "").trim() };
	}
	return { filter: null, rest: query.trim() };
}

function entryMatchesFilter(entry: ClipEntry, filter: string | null): boolean {
	if (!filter) return true;
	if (filter === "pinned") return entry.pinned === true;
	return entry.kind === filter;
}

// Subsequence fuzzy match. Returns a score (higher is better), or null if
// needle's characters don't all appear in haystack in order. Consecutive
// matches and matches at word boundaries score higher.
function fuzzyScore(haystack: string, needle: string): number | null {
	haystack = haystack.toLowerCase();
	needle = needle.toLowerCase();
	let ni = 0;
	let score = 0;
	let prevMatched = false;
	for (let hi = 0; hi < haystack.length && ni < needle.length; hi++) {
		if (haystack[hi] === needle[ni]) {
			score += 1;
			if (prevMatched) score += 4;
			const prev = hi > 0 ? haystack[hi - 1]! : " ";
			if (/[\s\W]/.test(prev)) score += 3;
			ni++;
			prevMatched = true;
		} else {
			prevMatched = false;
		}
	}
	return ni === needle.length ? score : null;
}

// ============================================================
// ROW FORMATTING
// ============================================================

function shorten(s: string, n: number): string {
	const trimmed = s.trim().replace(/\s+/g, " ");
	return trimmed.length > n ? trimmed.slice(0, n) + "…" : trimmed;
}

function humanBytes(n: number): string {
	if (n < 1024) return `${n} B`;
	if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
	return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function describeSize(entry: ClipEntry): string {
	if (entry.kind === "image") return `${entry.width}×${entry.height} · ${humanBytes(entry.bytes)}`;
	return humanBytes(entry.bytes);
}

function formattedTime(entry: ClipEntry): string {
	return new Date(entry.time).toLocaleString();
}

function buildSubText(entry: ClipEntry): string {
	const parts = [entry.kind as string];
	if (entry.source?.name) parts.push(`from ${entry.source.name}`);
	parts.push(formattedTime(entry));
	parts.push(describeSize(entry));
	if (entry.pinned) parts.push("pinned");
	return parts.join(" • ");
}

function rowTitle(entry: ClipEntry): string {
	if (entry.kind === "image") return `Image (${entry.width}×${entry.height})`;
	return shorten(entry.text ?? "", 120);
}

function appIcon(bundleID: string | null): HSImage | null {
	if (!bundleID) return null;
	const cached = iconCache.get(bundleID);
	if (cached !== undefined) return cached;
	const img = HSImage.fromAppBundle(bundleID);
	iconCache.set(bundleID, img);
	return img;
}

function rowImage(entry: ClipEntry): HSImage | null {
	if (entry.kind === "image" && entry.path) return HSImage.fromPath(entry.path);
	return appIcon(entry.source?.bundleID ?? null);
}

function searchableText(entry: ClipEntry): string {
	const body = entry.kind === "image" ? (entry.path?.match(/[^/]+$/)?.[0] ?? "") : (entry.text ?? "");
	return [body, entry.source?.name ?? "", formattedTime(entry), entry.kind].join(" ");
}

// ============================================================
// OPTIONS BAR (replaces the v1 Spoon's right-click context menu)
// ============================================================

function entryOptions(entry: ClipEntry): ChoiceOption[] {
	const options: ChoiceOption[] = [
		{ keyGlyph: "⏎", label: "Paste" },
		{
			mods: ["cmd"],
			key: "return",
			label: "Copy",
			run: () => {
				restoreEntry(entry);
				chooser?.hide();
			},
		},
		{
			mods: ["cmd"],
			key: ".",
			label: entry.pinned ? "Unpin" : "Pin",
			run: () => {
				entry.pinned = !entry.pinned;
				saveHistory();
				hs.ui.alert(entry.pinned ? "Pinned" : "Unpinned").duration(0.6).show();
				chooser?.refreshChoices();
			},
		},
		{
			mods: ["cmd"],
			key: "delete",
			label: "Delete",
			run: () => {
				const i = history.indexOf(entry);
				if (i !== -1) {
					deleteImageFile(entry);
					history.splice(i, 1);
				}
				saveHistory();
				chooser?.refreshChoices();
			},
		},
	];

	if (entry.kind === "image") {
		options.push({ mods: ["cmd"], key: "o", label: "Reveal in Finder", run: () => revealOrOpen(entry) });
	} else if (entry.kind === "url") {
		options.push({ mods: ["cmd"], key: "o", label: "Open URL", run: () => revealOrOpen(entry) });
	}

	return options;
}

// ============================================================
// CHOOSER
// ============================================================

function buildChoices(query: string): Record<string, unknown>[] {
	const { filter, rest } = parseQuery(query);
	const matches: { entry: ClipEntry; index: number; score: number }[] = [];
	history.forEach((entry, index) => {
		if (!entryMatchesFilter(entry, filter)) return;
		const score = rest === "" ? 0 : fuzzyScore(searchableText(entry), rest);
		if (score !== null) matches.push({ entry, index, score });
	});
	if (rest !== "") {
		matches.sort((a, b) => (b.score !== a.score ? b.score - a.score : a.index - b.index));
	}
	return matches.map(({ entry, index }) => ({
		text: rowTitle(entry),
		subText: buildSubText(entry),
		image: rowImage(entry),
		index,
	}));
}

function onSelect(choice: Record<string, unknown> | null, previouslyFocused: HSWindow | null): void {
	if (!choice) return;
	const entry = history[choice["index"] as number];
	if (!entry) return;
	// Deferred for the same reason as every other picker in this config:
	// onSelect fires mid-hide, so focusing + pasting synchronously here
	// races that handoff.
	hs.timer.doAfter(0, () => {
		previouslyFocused?.focus();
		paste(entry);
	});
}

function ensureLoaded(): void {
	if (chooser) return;
	chooser = hs.chooser.create();
	chooser.visibleRows = 10;
	chooser.width = 0.45;
	chooser.searchSubText = true;
	chooser.placeholder = "Search content, app, date… or :image / :url / :file / :pinned";
	chooser.backgroundColor = chooserColor(Theme.background);
	chooser.borderColor = chooserColor(Theme.border);
	chooser.cornerRadius = Theme.cornerRadius;
	chooser.textColor = chooserColor(Theme.text);
	chooser.subTextColor = chooserColor(Theme.textDim);
	chooser.setChoices(buildChoices);
	attachOptionsBar(chooser, (row) => {
		const entry = history[row["index"] as number];
		return entry ? entryOptions(entry) : undefined;
	});
}

export function show(): void {
	ensureLoaded();
	const c = chooser!;
	checkPasteboard(); // catch anything copied since the last change event
	if (history.length === 0) {
		hs.ui.alert("Clipboard history is empty").duration(1).show();
		return;
	}
	const previouslyFocused = hs.window.focusedWindow();
	c.onSelect = (choice) => onSelect(choice, previouslyFocused);
	c.query = "";
	c.show();
}

// ============================================================
// STARTUP
// ============================================================

hs.fs.mkdir(DATA_DIR);
hs.fs.mkdir(IMAGE_DIR);
history = loadHistory();
lastChangeCount = hs.pasteboard.changeCount;
hs.pasteboard.on("change", checkPasteboard);
